### ISSUE TITLE
authentication issue

### ISSUE THREAD

**Issue by ErickRyu** [adasq/google-alerts-api#10]
I tried two things about authentication issue explained in README. 

> https://accounts.google.com/DisplayUnlockCaptcha
> https://myaccount.google.com/lesssecureapps

But still authentication issue occur.
Is there something more have to do?

**Comment by adasq** [comment]
have you tried authenticate within a browser afterwards? Do you receive any Google-related security notification?

**Comment by ErickRyu** [comment]
I've got email which says that changed account access for less secure apps. In that email, I didn't click disallowing.

**Comment by adasq** [comment]
I just released 0.2.3 version.
Now, you have access to an internal method responsible for authentication. 
You can review, how does the HTTP authenticate response look like. 
Follow https://github.com/adasq/google-alerts-api#problem-with-authentication
Hope it will help with finding the issue reason.

**Comment by ErickRyu** [comment]
Thank you for updating.
I tried debug and get below.
```
302
{ 'content-type': 'text/html; charset=UTF-8',
  'x-frame-options': 'DENY',
  'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
  pragma: 'no-cache',
  expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
  date: 'Wed, 20 Jun 2018 02:12:02 GMT',
  location: 'https://accounts.google.com/signin/selectchallenge/2?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&flowName=GlifWebSignIn&TL=AHnYQLzJICo6V5C_dS8BNOW8wDsWe0I5xFM3auHG76ZNIVTEWnXGRD-9exs4PUxs54VoGpquDdgTFhqitZbAhTc9NwvFNkbv_JoPW9oflTI5vGtrU624AIuXi7CalBLvSNh-P5VJZdqSZA7cNVTZ7AWfqULLN6eWaA',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'content-security-policy': 'script-src \'report-sample\' \'nonce-P+OqFG+SPa0/QqRIN/CSvo4TEXU\' \'unsafe-inline\' \'strict-dynamic\' https: http: \'unsafe-eval\';object-src \'none\';base-uri \'self\';report-uri /cspreport',
  'content-length': '490',
  'x-content-type-options': 'nosniff',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'alt-svc': 'quic=":443"; ma=2592000; v="43,42,41,39,35"',
  connection: 'close' }
<HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Temporarily</H1>
The document has moved <A HREF="https://accounts.google.com/signin/selectchallenge/2?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&amp;flowName=GlifWebSignIn&amp;TL=AHnYQLzJICo6V5C_dS8BNOW8wDsWe0I5xFM3auHG76ZNIVTEWnXGRD-9exs4PUxs54VoGpquDdgTFhqitZbAhTc9NwvFNkbv_JoPW9oflTI5vGtrU624AIuXi7CalBLvSNh-P5VJZdqSZA7cNVTZ7AWfqULLN6eWaA">here</A>.
</BODY>
</HTML>
```

Above link takes me to the google my account page. I think it's my account setting problem not your code.
This issue occurs in my server. Using my laptop, my computer is allowed to login in google. So when I run the crawler in my laptop, It works. But when I run the same code in my server, It doesn't works and occurs authentication issue.

Can I get some hint about this?

**Comment by adasq** [comment]
Correct, it's pure authentication issue. What I'm concern about is your `location` header url.
It starts with `https://accounts.google.com/signin/selectchallenge/2`
I guess it's related to this:
https://support.google.com/a/answer/6002699?hl=en&ref_topic=7556906
But that might suggest, that you are using G Suite-based account. In theory, you can "Disabling the challenge" (search for this in the page) but it requires access to an admin panel... Is it a case for you?

**Comment by ErickRyu** [comment]
I'm not using G Suite-based account. so I can't access to an admin panel and can't "Disabling the challenge". I think It's not my case...

**Comment by ErickRyu** [comment]
I tried again https://accounts.google.com/b/0/DisplayUnlockCaptcha within secret mode and it works.
I think I tried with wrong account.

**Comment by adasq** [comment]
Thank you for clarification.
