### ISSUE TITLE
Login with Google Auth

### ISSUE THREAD

**Issue by fabiobeoni** [adasq/google-alerts-api#11]
Hello adasq,
thanks for this module, really nice and interesting.

I'm wondering if it is possible to skip login with password if the user is already logged with Google Auth.

Thanks, cheers.

**Comment by adasq** [comment]
You can always pass cookies string instead of email/password pair.

**Comment by fabiobeoni** [comment]
Hi,

using `alerts.configure({cookies:xxxxxx})` I get a JSON parsing error into **_api.js_** file:

```
function parseCookies(cookies) {
    const str = new Buffer(cookies, 'base64').toString('ascii');
    return JSON.parse(str);  **<===== PARSE ERROR HERE**
}
```

The cookie is generated by Firebase Admin SDK (since I use Firebase with Google Auth to login users) as described [here](https://firebase.google.com/docs/auth/admin/manage-cookies).

**Comment by adasq** [comment]
`alerts.configure({cookies:xxxxxx})` requires cookie generated from the lib, retrived using `alerts.generateCookies`. You can not pass there any other cookies, including side services such as Firebase.

more here:
https://github.com/adasq/google-alerts-api#generate-cookies

Unfortunately there is no other way to authenticate.
