### ISSUE TITLE
authentication issue 

### ISSUE THREAD

**Issue by Sikandarkhan** [adasq/google-alerts-api#14]
Facing an authentication issue. We have followed all the possibilities mentioned here in URL, [https://www.npmjs.com/package/google-alerts-api#problem-with-authentication](https://www.npmjs.com/package/google-alerts-api#problem-with-authentication ) 

```
api.reqHandler.login({
mail: 'xxxxxxxxx@gmail.com',
password: 'xxxxxx'
}, (err, debug) => {
fs.writeFileSync('login.html', debug.body);
// For success, this should be short and include "LoginDoneHtml" and "Moved Temporarily" text inside.
});

```

![a](https://user-images.githubusercontent.com/7334929/46950378-2642ee00-d0a2-11e8-9567-841eeab470da.png)

**Comment by dotjose** [comment]
I'm facing the same problem here.

**Comment by adasq** [comment]
It is hars to reproduce but I will give it’s a try. Doesn’t simple form filling solve the problem?

**Comment by dotjose** [comment]
How? When you try to login with your devices it doesn't ask any captcha or something. I'm facing this only when I use this api.

**Comment by jayu-git** [comment]
Facing with the same issue, Is there any way to bypass it.

**Comment by jayu-git** [comment]
Did anyone get the solution for this?
I have also enabled less secured app setting and also did displayunlockcaptcha, still facing the issue.

**Comment by adasq** [comment]
Dear 

New version `0.4.0` has been published. A solution I have came with is to require a CAPTCHA to be retyped by you within a command line.

I do recommend using [alerts.generateCookies](https://github.com/adasq/google-alerts-api#generate-cookies) to fill CAPTCHA once, and then reuse cookies each time you want to interact witn an API.

Thanks you @Sikandarkhan, @dotjose and @jayu-git for your comments raising the issue and sorry for a delay with providing the fix.

If you face any issue, feel free to post details here.

**Comment by jayu-git** [comment]
Thank you very much @adasq, working fine now.

**Comment by Sikandarkhan** [comment]
Awesome. It's working fine. Thank you @adasq

**Comment by mrSidX** [comment]
Hello,  

I had used your google-alerts-api module to generate and return an RSS feed based on giving it it a keyword argument... A day or so ago It was working nicely,  and today I'm having authentication errors.  

I try this on two different accounts and getting the same error.

I was wondering if anyone has been having this issue as of late?
