### ISSUE TITLE
Unable to authenticate in order to generate cookies

### ISSUE THREAD

**Issue by maxkorytko** [adasq/google-alerts-api#17]
Hi,

Thank you very much for this library!

It looks like other people had issues with authentication as well, and I did review all the previous issues, but nothing worked for me, unfortunately.

I started using 'google-alerts-api' back in 2017 (using version 0.2.0), and it has been working great. I now need to switch to another Google account, so I'm trying to generate a new cookie, and this is what is not working for me.

Here is my code:

```javascript
function generateCookies({ email, password }) {
  return new Promise((resolve, reject) => googleAlertsApi.generateCookies(
    email,
    password,
    (error, newCookies) => (error ? reject(error) : resolve(newCookies)),
  ));
}

function debugCookies({ email, password }) {
  return new Promise((resolve, reject) => {
    googleAlertsApi.reqHandler.login(
      {
        mail: email,
        password,
      },
      (error, debug) => (error ? reject(error) : resolve(debug)),
    );
  });
}
```
The call to `generateCookies` returns an error: `authentication issue`.
The call to `debugCookies` prints this to the console:
```
Debug Info
Status code: 302
Headers: { 'content-type': 'text/html; charset=UTF-8',
  'x-frame-options': 'DENY',
  'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
  pragma: 'no-cache',
  expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
  date: 'Sun, 13 Jan 2019 13:44:12 GMT',
  location: 'https://accounts.google.com/signin/rejected?hl=en-GB&rrk=47&rhlk=js',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'content-security-policy': 'script-src \'report-sample\' \'nonce-zqxueHHy0EUL0L2YK1TjUQ\' \'unsafe-inline\' \'unsafe-eval\';object-src \'none\';base-uri \'self\';report-uri /cspreport',
  'content-length': '257',
  'x-content-type-options': 'nosniff',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'set-cookie':
   [ 'GAPS=1:R2RFVmc9IBTk3vt_ogFDaxHf7Elj_g:Wxfg3oYSGANTDWXz;Path=/;Expires=Tue, 12-Jan-2021 13:44:12 GMT;Secure;HttpOnly;Priority=HIGH' ],
  'alt-svc': 'quic=":443"; ma=2592000; v="44,43,39,35"',
  connection: 'close' }
Body: <HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Temporarily</H1>
The document has moved <A HREF="https://accounts.google.com/signin/rejected?hl=en-GB&amp;rrk=47&amp;rhlk=js">here</A>.
</BODY>
</HTML>
```

I've tried doing this: https://www.npmjs.com/package/google-alerts-api#generate-cookies.

Any ideas?

Thanks!

**Comment by adasq** [comment]
You are right. I think it is related to the fact, that google no longer allows to authenticate with disabled JS (the package relays on it). If you want quick-win solution, here is a way to do it:

1. Run "Dev Tools" tools and navigate "Network" tab
2. Log in to Google
3. Filter for "/signin/sl/challenge" pattern request
4. In "Response" section search for "set-cookie: " entries. You will need 3 values: SID (71 characters), HSID, SSID (both 17 characters). Then you can use it to generate cookies, just run the function with your variables:

```js
    function generateCookies(SID, HSID, SSID) {
        const str = JSON.stringify(
            [
                { key: 'SID', value: SID, domain: 'google.com' },
                { key: 'HSID', value: HSID, domain: 'google.com' },
                { key: 'SSID', value: SSID, domain: 'google.com' },
            ]
        );
        return new Buffer(str).toString('base64');
    }
```

Then, put this output to "cookies" configuration. Thanks for your notification!

**Comment by maxkorytko** [comment]
Hi @adasq , 
Thanks! I'll give this solution a shot. Will keep you posted.

**Comment by maxkorytko** [comment]
Hi @adasq ,

It worked! Thanks.

**Comment by adasq** [comment]
Ok, closing, thanks for raising the issue! Will link this trick into README.md
