### ISSUE TITLE
Not able to login with my correct credentails, throw some "moved temporarily" error 

### ISSUE THREAD

**Issue by assadvirgo** [adasq/google-alerts-api#18]
I tried to login with my correct credentials but got following error which i ran following code 

reqHandler.login({
    mail: MAIL,
    password: PASSWORD
}, (err, debug) => {
    console.log(debug.statusCode); 
    // For success, you should see here '302'.
    console.log(debug.headers); 
    // For success, in 'set-cookie' header content, you should see SID, LSID, HID, SSID (etc.) definitions.
    console.log(debug.body); 
    // For success, this should be short and include "LoginDoneHtml" and "Moved Temporarily" text inside.
});

## ERROR

302
{ 'content-type': 'text/html; charset=UTF-8',
  'x-frame-options': 'DENY',
  'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
  pragma: 'no-cache',
  expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
  date: 'Mon, 18 Feb 2019 06:05:45 GMT',
  location:
   'https://accounts.google.com/signin/rejected?hl=en-GB&rrk=47&rhlk=js',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'content-security-policy':
   "script-src 'report-sample' 'nonce-+HbaFxf5NKhmo/0ETbtp3A' 'unsafe-inline' 'unsafe-eval';object-src 'none';base-uri 'self';report-uri /cspreport",
  'content-length': '257',
  'x-content-type-options': 'nosniff',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'alt-svc': 'quic=":443"; ma=2592000; v="44,43,39"',
  connection: 'close' }
<HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Temporarily</H1>
The document has moved <A HREF="https://accounts.google.com/signin/rejected?hl=en-GB&amp;rrk=47&amp;rhlk=js">here</A>.
</BODY>
</HTML>

**Comment by adasq** [comment]
Please try authenticate with the way described here:

https://github.com/adasq/google-alerts-api/issues/17#issuecomment-453865203

**Comment by assadvirgo** [comment]
@adasq Thanks it helped.
