### ISSUE TITLE
does not allow to create alerts

### ISSUE THREAD

**Issue by MauricioDonoso** [adasq/google-alerts-api#19]
4|index  | TypeError: Cannot read property '3' of null
4|index  |     at Object.getRequestXByState (/var/www/***/node_modules/google-alerts-api/src/alerts.js:193:17)
4|index  |     at Object.create (/var/www/***/node_modules/google-alerts-api/src/api.js:109:29)
4|index  |     at alerts.sync (/var/ww/***/controllers/googlealerts/googlealerts.js:410:38)
4|index  |     at Request.getCb [as _callback] (/var/www/***/node_modules/google-alerts-api/src/api.js:67:28)
4|index  |     at Request.self.callback (/var/www/***/node_modules/google-alerts-api/node_modules/request/request.js:188:22)
4|index  |     at emitTwo (events.js:126:13)
4|index  |     at Request.emit (events.js:214:7)
4|index  |     at Request.<anonymous> (/var/www/***/node_modules/google-alerts-api/node_modules/request/request.js:1171:10)
4|index  |     at emitOne (events.js:116:13)
4|index  |     at Request.emit (events.js:211:7)
4|index  |     at IncomingMessage.<anonymous> (/var/www/***/node_modules/google-alerts-api/node_modules/request/request.js:1091:12)
4|index  |     at Object.onceWrapper (events.js:313:30)
4|index  |     at emitNone (events.js:111:20)
4|index  |     at IncomingMessage.emit (events.js:208:7)
4|index  |     at endReadableNT (_stream_readable.js:1055:12)

**Comment by adasq** [comment]
Hi,

I see Google has updated the way an alert is being managed a couple of days ago. Will try to fix it.

**Comment by MauricioDonoso** [comment]
Thanks, I'll be attentive to the changes

**Comment by adasq** [comment]
FYI, work in progress:
https://github.com/adasq/google-alerts-api/tree/google-changes-adjustments

**Comment by adasq** [comment]
`google-alerts-api@0.4.2` has been published. Feel free to reopen issue if you face any problem.
