### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by annonip** [adasq/google-alerts-api#3]
Sometimes usually when I do more than 10 requests, I get authentication issue and of course any method like create an alert or get alerts works.

Any ideas?

**Comment by adasq** [comment]
What do you mean by "do more than 10 requests"? Calling `sync` method 10 times in a row? What kind of authentication are you using? mail+password or cookies?

**Comment by annonip** [comment]
Yes, for example using postman. I create 10 or more Alerts.
Then, I get Authentication issue.
In theory Im using mail+pass+cookies, but I have to do in this way:
`
alerts.configure({
 mail: mail,
 password: password,
 cookies: fs.readFileSync('cookies.data').toString()
});

fs.writeFileSync('cookies.data', alerts.getCookies());`

because using the method `alerts.generateCookies ` always go into:  `if(err) return console.log(err);` 'couse the cookie is undefined.

**Comment by adasq** [comment]
What comes to my mind, is that you are trying to authenticate 10x times in shot period, which is permitted by Google.

I would love to see some working piece of code which covers your problems.

**Comment by adasq** [comment]
Closing, if still does not work, feel free to reopen.
