### ISSUE TITLE
Keeping Session Keys Alive

### ISSUE THREAD

**Issue by mrSidX** [adasq/google-alerts-api#30]
I know this might not be an issue with the package or such, but I was curious if anyone was able to circumvent the expiration of the credentials / SID's  ,  as mine are expiring after a few days, even if I utilize the keys every minute ( using a method to check if it's alive or not ).

Any feed back is greatly appreciated.

**Comment by adasq** [comment]
Hey, 
For library testing purpose I run tests [once a weekday](https://github.com/adasq/google-alerts-api/blob/master/.github/workflows/nodejs.yml#L8) and have never encountered session expiration issue, so daily "health check" seem to be enough.

I do use a dedicated account for this. You can create another one and check how it works.

Thank you for your message.
