### ISSUE TITLE
How to set proxy?

### ISSUE THREAD

**Issue by ankurchavda** [adasq/google-alerts-api#33]
Is there a way to set proxy for networks that are behind a firewall? I want to use this library but because I am not well versed with Node I am not sure how to set a proxy.

**Comment by adasq** [comment]
It's more related to nodejs itself rather than this package. I'am not familiar with proxying at all. Please, see https://github.com/http-party/node-http-proxy

**Comment by ankurchavda** [comment]
Not talking about creating a proxy server but more about this https://stackoverflow.com/a/21281075. I hope this throws more light on what I am talking about.

**Comment by ankurchavda** [comment]
Hi, can you please help me around this or guide me on how can I make this change in the code base? I am happy to do that too.
