### ISSUE TITLE
Authorization Issue

### ISSUE THREAD

**Issue by mailspider** [adasq/google-alerts-api#34]
Hi,
I face the following odd behavior.
I log in to Google with my account (chrome browser) and copy SID, HSID, SSID form the application-cookies section in dev tools of the session. I keep the Google session open and configure my application to use the IDs. Authorization works well (alerts.js line 63 indexof @ is 2683 isLoggedIn is true). I can create modify and read the alerts.
I now log out of my Google account and close the browser window. Now the authorization fails. The html content of body (api.js line 69) contains a "SignIn" Button. 
Interestingly, I have a set IDs I copied beginning of September. With these IDs I can authorize without having an open Google Account session. Any new set of IDs works only as long as the Google Account session the IDs are copied from is open. If I close the session I cannot log in anymore using the IDs. 

What do I wrong?

Thanks for any advise.   
Best regards
Andreas

**Comment by adasq** [comment]
Hey Andreas,

Thanks for describing your case. 
If by saying "closing session" you mean logging out from the account, it's obvious that your session will be removed - so you will not be able to reuse those IDs anymore.

If you want to create "long-living" IDs, best option is to use "_Incognito mode_". Just authenticate, copy your IDs and close the browser w/o logging out from the account.

It is hard to say how does the Google authentication process work under the hood. I just authenticated in "_Incognito mode_" which generated me a new set of IDs, and it works fine. Unfortunately, my old IDs stopped to work on my local machine... but still works on Github for "_google-alerts-api CI_"... 

It's weird.

**Comment by mailspider** [comment]
Hi
Thanks for your fast reply and you comments.
It helps!
Best regards
Andreas
