### ISSUE TITLE
create is returning 'undefined'

### ISSUE THREAD

**Issue by ankurchavda** [adasq/google-alerts-api#35]
Wanted to test creating an alert with the following parameters but `console.log(alert)` gives **undefined** as an output.

```
alerts.sync(() => {
    const alertToCreate = {
    	howOften: HOW_OFTEN.AS_IT_HAPPENS,
	sources: SOURCE_TYPE.AUTOMATIC,
        lang: 'en',
        name: 'NodeJS AND "Chrome V8"',
        region: 'any'
        howMany: HOW_MANY.ALL,
        deliverTo: DELIVER_TO.RSS,
        deliverToData: ''
    };

    alerts.create(alertToCreate, (err, alert) => {
        console.log(alert);
    });
});
```

**Comment by adasq** [comment]
please what's inside `err`

**Comment by ankurchavda** [comment]
It is because of the `region:'any'` property. err had something like **typeerror 'caller' 'callee' and 'arguments'**. I am not very adept with Node so pardon if I don't make a lot of sense.

**Comment by adasq** [comment]
are you authenticated before calling `sync()`?

**Comment by ankurchavda** [comment]
Yes, I am. It is because of the `region: any` property. If specify a region, let's say 'PL' as mentioned in the example, it won't cause an issue. Then it runs perfectly fine and I am able to create the alert.

**Comment by adasq** [comment]
Can you please check creating an alert with exact configuration as in unit tests?

https://github.com/adasq/google-alerts-api/blob/master/tests/test.js#L68-L77

**Comment by ankurchavda** [comment]
I tried the following and still, it returns `undefined`.

```
 const alertToCreate = {
                        name: 'Any Test',
                        howOften: HOW_OFTEN.AT_MOST_ONCE_A_DAY,
                        sources: SOURCE_TYPE.AUTOMATIC,
                        lang: 'en',
                        region: 'any',
                        howMany: HOW_MANY.BEST,
                        deliverTo: DELIVER_TO.RSS,
                        deliverToData: '',
                    };
```

**Comment by adasq** [comment]
Hey, sorry you had to wait. I checked it and it works for me.

Is it possible, that alert with name `Any Test` already exists on your list? We can't create two the same alerts. Please, let me know it is a reason of an issue.

**Comment by ankurchavda** [comment]
Unfortunately, there's no other alert with the name `Any Test`. I tried this on two different systems as well. Same issue. As soon as I change the region value from `any` to `PL`, it starts working.

**Comment by adasq** [comment]
Can u send me your "create alert" request body? 
It's `POST` `https://www.google.pl/alerts/create?x=...`

**Comment by ankurchavda** [comment]
I am not sure how to use it from the web interface.

**Comment by adasq** [comment]
Are you familiar with dev-tools for browser?
Here is an example how to check request body from  `google.com/alerts` web interface
![image](https://user-images.githubusercontent.com/5637734/112728992-34132380-8f2a-11eb-8271-153985c7d756.png)

**Comment by ankurchavda** [comment]
```
[
  null,
  [
    null,
    null,
    null,
    [
      null,
      "Any Test",
      "com",
      [
        null,
        "en",
        "any",
      ],
      null,
      null,
      null,
      1,
      1,
    ],
    null,
    3,
    [
      [
        null,
        2,
        "",
        [
          null,
          null,
          19,
        ],
        2,
        "pl-US",
        null,
        null,
        null,
        null,
        null,
        "0",
        null,
        null,
        "*****************Removed Intentionally******************",
      ],
    ],
    null,
    null,
    null,
  ],
]
```

I got the form body using debugger. Does this help?

**Comment by adasq** [comment]
It's from `nodejs` app, right? 
I asked about form body, which is generated by real Google Alerts webapp.

**Comment by ankurchavda** [comment]
![image](https://user-images.githubusercontent.com/13657423/112731708-57f05c80-8f5e-11eb-9d6e-e183eacb7754.png)

Hope this helps

**Comment by adasq** [comment]
It's really hard to debug remotely, but let's try :)
Thanks for your input. But the second screen seem to have completely different configuration. Can you please upload `body` for alert with configuration causing an issue to you? I guess this one is problematic:

```
name: 'Any Test',
howOften: HOW_OFTEN.AT_MOST_ONCE_A_DAY,
sources: SOURCE_TYPE.AUTOMATIC,
lang: 'en',
region: 'any',
howMany: HOW_MANY.BEST,
deliverTo: DELIVER_TO.RSS,
deliverToData: '',
```

**Comment by ankurchavda** [comment]
I just changed the name from `Any Test` to `Dev Tools` because I created one alert for Any Test with `region:PL`.  Everything else is the same. 

I deleted `Any Test` and have created one more alert with the above settings as seen below. And thanks for bearing with me all this while. Appreciate it.

![image](https://user-images.githubusercontent.com/13657423/112733337-7dcd2f80-8f65-11eb-8fe5-7eebfb6bc9d0.png)

**Comment by adasq** [comment]
Cannot reproduce it on my side.

What I can recommend is to play around `./node_modules/google-alerts-api/src/alerts.js` (`create()` function).

You can start with updating returned object, i.e. by introducing changes to align a body you posted [here](https://github.com/adasq/google-alerts-api/issues/35#issuecomment-808794802) with a object returned by `create()` function. There are some discrepancies, i.e.: `google-alerts-api` has `pl-EN` fixed out there. In your case there is `en-IN`.

If you find any field which does the job, let me know so we can come up with some ideas how to  tackle the issue.

**Comment by ankurchavda** [comment]
So does this mean that If choose `any`, google alerts is picking up `IN` as the region?

**Comment by adasq** [comment]
Over here we have also fixed `US` for `any` region:
https://github.com/adasq/google-alerts-api/blob/master/src/alerts.js#L168

**Comment by ankurchavda** [comment]
Hey, sorry couldn't respond to this sooner. Kill me if you will, I found out I was not using the latest version of this library. Will close this issue. Apologies for holding you up all this while.

I just have one more question before we close this if you can help. When I create the alert from UI using `any` region, the form has `IN` specified when check in dev tools. Maybe because I am using it from India. However, if I pass `IN` in the library, the alerts I get for both are different. Is this because the `any` region takes into account the current region you are in as well as any relevant articles it can get from other regions as well?
