### ISSUE TITLE
Beating the Google captcha

### ISSUE THREAD

**Issue by donstefani** [adasq/google-alerts-api#42]
First I want to say this app works great, thank you for it.
I've got everything working great, I have about 150 to 200 alerts that I am adding per run.
It works great _once_, then I get shut out by the captcha. On my alerts account I see a yellow banner that says the server is unreachable. When I refresh I get a captcha. This happened yesterday when I was testing. This morning I was able to run it just fine, and then when I tried to fetch the alerts I was blocked.

I tried the unlock captcha but even if I use the captcha I'm blocked after one use.

Has anyone found a way around this?

**Comment by adasq** [comment]
Hey there,

Thanks for reaching out. Personally, I haven't faced the issue.
It's hard to say how does the Google security logic works under the hood it could be either:

- different execution location (your local machine / your CI / your 3rd party server), or
- too many requests in a short period of time, or
- anything else...

Cheers.
