### ISSUE TITLE
return state[state.length - 4] TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by stylessh** [adasq/google-alerts-api#46]
Throws this error sometimes while adding new alert.

###  Screenshot
![image](https://user-images.githubusercontent.com/45767683/146833134-9657505a-5713-48dd-b78d-8621c66e91ec.png)

**Comment by MauricioDonoso** [comment]
same problem

**Comment by stylessh** [comment]
Didn't found any way to fix this, I had to create a script that restart the server each time the library throws this error.

**Comment by adasq** [comment]
Hey 👋🏻 

Are you sure you call `sync()` before `create()`?
It looks like the internal's `state` reference is `null`. It's a case only before authenticating.

**Comment by stylessh** [comment]
> Hey 👋🏻
> 
> Are you sure you call `sync()` before `create()`? It looks like the internal's `state` reference is `null`. It's a case only before authenticating.

Yes, I was synced once. Then looping through each request to create a new alert. It works perfectly, but sometimes from nowhere just throws this error.

**Comment by altancodes** [comment]
I have the same issue. Did any of you find the reason why there is a problem?

**Comment by stylessh** [comment]
Not really, I just made a webhook that restarts the server each time it crashes...

> I have the same issue. Did any of you find the reason why there is a problem?
