### ISSUE TITLE
How to select ANY REGION?

### ISSUE THREAD

**Issue by Sikandarkhan** [adasq/google-alerts-api#7]
I have been trying to select ANY_REGION from this npm module 

Any inputs, would be appreciable

**Comment by adasq** [comment]
Just do not specify `region` property at all. 
And correct, that might be not obvious, so I updated README.
Thanks for signaling. 
Closing.
Feel free to reopen if it requires any further actions.

**Comment by Sikandarkhan** [comment]
By default it is considering as, US region then.?

**Comment by adasq** [comment]
the best way to set Any region is to not pass region property at all. It can help you. I will try to fix the issue soon.

**Comment by adasq** [comment]
Support for "All Region" added. 
While getting alert, you will see `region` set as `"any"`. 
While creating alert, simply add `region: "any"` or do not specify it at all.
Changes published as `google-alerts-api@0.6.0`.
Closing.

**Comment by Sikandarkhan** [comment]
Amazing news. Good to hear that.
