### ISSUE TITLE
Running the code from AWS Lambda

### ISSUE THREAD

**Issue by salshyn** [adasq/google-alerts-api#9]
Hi @adasq,
The code runs locally, but not from Lambda (authentication issue). Any ways to fix you know?
Thanks.

**Comment by adasq** [comment]
Have you tried what I have written here: https://github.com/adasq/google-alerts-api/issues/8 ?

**Comment by salshyn** [comment]
Issue fixed. Long story short: https://accounts.google.com/DisplayUnlockCaptcha
